# Generated by Django 3.2.4 on 2021-06-29 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0002_auto_20210627_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='marked_as_right',
            field=models.BooleanField(default=False),
        ),
    ]
